### ISSUE TITLE
Port forwarding p2p connections requires port 13000. 

### ISSUE THREAD

**Issue by DigiDr** [prysmaticlabs/prysmaticlabs.gitbook.io#5]
In order to get incoming connections from peers, port 13000 should be open from router/firewall to host. 

If running on docker, present instructions say 

docker run -it -v $HOME/prysm/beacon:/data -p 4000:4000 \
  gcr.io/prysmaticlabs/prysm/beacon-chain:latest \
  --datadir=/data

Please add -p 13000:13000 to enable docker host to forward 13000 to container appropriately.

**Comment by har00ga** [comment]
Hi, thanks for noting this issue!! We are currently in the process of migrating off of the Gitbook documentation portal and onto a self-hosted static serve option (found [here](https://github.com/prysmaticlabs/documentation)), it will be live later this weekend. If you wouldn't mind filing this issue under the new repository, I will be sure to address it once the portal is public. :slightly_smiling_face:
